.TH LYNX_PARSE 1 "August 15, 2001" xbel-utils "User's Manual"
.SH NAME
lynx_parse \- a simple utility to convert Lynx bookmarks to XBEL

.SH SYNOPSIS
.B lynx_parse
\fIDIRECTORY\fR [\fIOUTFILE\fR]

.SH DESCRIPTION
The XML Bookmark Exchange Language, or XBEL, is an Internet "bookmarks"
interchange format. \fBlynx_parse\fR parses Lynx bookmark files.

.SH USAGE
\fBmsie_parse\fR takes a Lynx \fIDIRECTORY\fR as input and
prints the XBEL representation to stdout, unless \fIOUTFILE\fR was specified.

.SH REQUIRES
Python

.SH "SEE ALSO"
.B adr_parse(1), msie_parse(1), lynx(1), ns_parse(1), xbel_parse(1), xbel2html(1)

.I http://pyxml.sourceforge.net/topics/xbel/

.SH AUTHOR
Python XML Special Interest Group (XML-SIG)

This man-page was written by Jan Schaumann <jschauma@netmeister.org> as part of "The Missing
Man Pages Project".  Please see \fIhttp://www.netmeister.org/misc/m2p2/index.html\fR
for details.
