.TH MSIE_PARSE 1 "August 15, 2001" xbel-utils "User's Manual"
.SH NAME
msie_parse \- a simple utility to convert MS Internet Explorer bookmarks to XBEL

.SH SYNOPSIS
.B msie_parse
\fIPATH-TO-FAVORITES\fR

.SH DESCRIPTION
The XML Bookmark Exchange Language, or XBEL, is an Internet "bookmarks"
interchange format. \fBmsie_parse\fR parses Microsoft Internet Explorer
bookmark files.

.SH USAGE
\fBmsie_parse\fR takes the path to your \fIFAVORITES\fR folder as input and
prints the XBEL representation to stdout.

.SH REQUIRES
Python

.SH "SEE ALSO"
.B adr_parse(1), lynx_parse(1), ns_parse(1), xbel_parse(1), xbel2html(1)

.I http://pyxml.sourceforge.net/topics/xbel/

.SH AUTHOR
Python XML Special Interest Group (XML-SIG)

This man-page was written by Jan Schaumann <jschauma@netmeister.org> as part of "The Missing
Man Pages Project".  Please see \fIhttp://www.netmeister.org/misc/m2p2/index.html\fR
for details.
