.TH XBEL2HTML 1 "August 15, 2001" xbel-utils "User's Manual"
.SH NAME
xbel2html \- a simple utility to convert XBEL files HTML

.SH SYNOPSIS
.B xbel2html
\fIINFILE\fR

.SH DESCRIPTION
The XML Bookmark Exchange Language, or XBEL, is an Internet "bookmarks"
interchange format. \fBxbel2html\fR parses XBEL files and generates a valid
HTML file.

.SH USAGE
\fBxbel2html\fR reads the specified \fIINFILE\fR and prints HTML to stdout.

.SH REQUIRES
Python

.SH "SEE ALSO"
.B adr_parse(1), msie_parse(1), lynx(1), lynx_parse(1), ns_parse(1), xbel_parse(1)

.I http://pyxml.sourceforge.net/topics/xbel/

.SH AUTHOR
Python XML Special Interest Group (XML-SIG)

This man-page was written by Jan Schaumann <jschauma@netmeister.org> as part of "The Missing
Man Pages Project".  Please see \fIhttp://www.netmeister.org/misc/m2p2/index.html\fR
for details.
