#!/bin/sh

# Set these paths appropriately

BIN=/home/ollagnier/Documents/tools/bilbo-utf8-LastV/bilbo/dependencies/tree-tagger-linux-3.2/bin
CMD=/home/ollagnier/Documents/tools/bilbo-utf8-LastV/bilbo/dependencies/tree-tagger-linux-3.2/cmd
LIB=/home/ollagnier/Documents/tools/bilbo-utf8-LastV/bilbo/dependencies/tree-tagger-linux-3.2/lib

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/tokenize.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/german-abbreviations
PARFILE=${LIB}/german.par
LEXFILE=${LIB}/german-lexicon.txt
FILTER=${CMD}/filter-german-tags

$TOKENIZER -a $ABBR_LIST $* |
# external lexicon lookup
perl $CMD/lookup.perl $LEXFILE |
# tagging
$TAGGER $OPTIONS $PARFILE  | 
# error correction
$FILTER
