#!/bin/sh

# Set these paths appropriately

BIN=/home/ollagnier/Documents/tools/bilbo-utf8-LastV/bilbo/dependencies/tree-tagger-linux-3.2/bin
CMD=/home/ollagnier/Documents/tools/bilbo-utf8-LastV/bilbo/dependencies/tree-tagger-linux-3.2/cmd
LIB=/home/ollagnier/Documents/tools/bilbo-utf8-LastV/bilbo/dependencies/tree-tagger-linux-3.2/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/tokenize.pl
MWL=${CMD}/mwl-lookup-greek.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/greek.par

$TOKENIZER $* |
# recognition of MWLs
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

