#!/bin/sh

# Set these paths appropriately

BIN=/home/ollagnier/Documents/tools/bilbo-utf8-LastV/bilbo/dependencies/tree-tagger-linux-3.2/bin
CMD=/home/ollagnier/Documents/tools/bilbo-utf8-LastV/bilbo/dependencies/tree-tagger-linux-3.2/cmd
LIB=/home/ollagnier/Documents/tools/bilbo-utf8-LastV/bilbo/dependencies/tree-tagger-linux-3.2/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
