#!/bin/sh

# Set these paths appropriately

BIN=/home/ollagnier/Documents/tools/bilbo-utf8-LastV/bilbo/dependencies/tree-tagger-linux-3.2/bin
CMD=/home/ollagnier/Documents/tools/bilbo-utf8-LastV/bilbo/dependencies/tree-tagger-linux-3.2/cmd
LIB=/home/ollagnier/Documents/tools/bilbo-utf8-LastV/bilbo/dependencies/tree-tagger-linux-3.2/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
