#!/bin/sh

# Set these paths appropriately

BIN=/home/ollagnier/Documents/tools/bilbo-utf8-LastV/bilbo/dependencies/tree-tagger-linux-3.2/bin
CMD=/home/ollagnier/Documents/tools/bilbo-utf8-LastV/bilbo/dependencies/tree-tagger-linux-3.2/cmd
LIB=/home/ollagnier/Documents/tools/bilbo-utf8-LastV/bilbo/dependencies/tree-tagger-linux-3.2/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/tokenize.pl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/spanish-abbreviations
PARFILE=${LIB}/spanish.par
MWLFILE=${LIB}/spanish-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE

